name: Build an application

inputs:
  ARTIFACT_ID:
    required: true
    description: ''
  MODULE_PATH:
    required: false
    default: .

outputs:
  VERSION:
    value: ${{ steps.version.outputs.VERSION }}
    description: ''
  ARTIFACT_PATH:
    value: ${{ steps.build.outputs.ARTIFACT_PATH }}
    description: ''

runs:
  using: "composite"
  steps:

    - name: Print Inputs
      run: |
        echo "===================="
        echo "ARTIFACT_ID=${{ inputs.ARTIFACT_ID }}"
        echo "======================"
      shell: bash

    - name: Rewrite version
      id: version
      run: |
        DATE_TIME=$(date '+%Y.%m.%d.%H.%M')
        SHA8=$(git rev-parse --short HEAD)
        VERSION="${DATE_TIME}-${SHA8}"
        find ${{ inputs.MODULE_PATH }} -name 'build.gradle.kts' -exec sed -i "s/APPOINTMENT-BOOKING-UNSET-VERSION/${VERSION}/g" {} +
        echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "VERSION=${VERSION}"
      shell: bash
      env:
        TZ: Africa/Johannesburg

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
          java-version: '21'
          distribution: 'temurin' # 'temurin' is the standard open-source JDK
          cache: 'gradle'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-kotlin-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-kotlin-

    - name: Create Gradle directories
      run: |
        mkdir -p ~/.gradle/caches
        mkdir -p ~/.gradle/wrapper
      shell: bash

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('**/AppointmentBookingApplicationTests.java') }}

    - name: Pull Docker images for tests
      run: |
        docker pull postgres:17 &
        docker pull quay.io/keycloak/keycloak:26.1.2 &
        docker pull confluentinc/cp-kafka:7.7.6 &
        docker pull wiremock/wiremock:latest &
        wait
      shell: bash

    - name: Test with Gradle
      id: test
      run: ./gradlew clean test   --no-daemon --max-workers=1
      shell: bash

    - name: Build with Gradle
      id: build
      run: |
        ./gradlew clean build  -x test --console=plain --no-daemon  -DexcludedTags=kafka
        ARTIFACT_PATH=$(pwd)/build/libs/${ARTIFACT_ID}-${VERSION}.jar
        echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> "$GITHUB_OUTPUT"
        echo "ARTIFACT_PATH=${ARTIFACT_PATH}"
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
        ARTIFACT_ID: ${{ inputs.ARTIFACT_ID }}

    - name: Print Outputs
      run: |
        echo "=============="
        echo "VERSION: ${{ steps.version.outputs.VERSION }}" 
        echo "ARTIFACT_PATH: ${{ steps.build.outputs.ARTIFACT_PATH }}" 
        echo "==============="
      shell: bash

    - name: Create Text Summary of Failures
      if: failure()
      run: |
        # Find all XML result files and extract the failure messages into a txt file
        grep -hR "failure message" build/test-results/test/*.xml > test-failures.txt || echo "No failures found" > test-failures.txt
      shell: bash

    - name: Upload Text Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-failures-text
        path: test-failures.txt
    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_ID }}-${{ steps.version.outputs.VERSION }}
        path: ${{ steps.build.outputs.ARTIFACT_PATH }}
        retention-days: 1