name: Build an application

inputs:
  ARTIFACT_ID:
    required: true
    description: 'The artifact ID for the build'
  MODULE_PATH:
    required: false
    default: .
    description: 'Path to the module to build'

outputs:
  VERSION:
    value: ${{ steps.version.outputs.VERSION }}
    description: ''
  ARTIFACT_PATH:
    value: ${{ steps.build.outputs.ARTIFACT_PATH }}
    description: ''

runs:
  using: "composite"
  steps:

    - name: Print Inputs
      run: |
        echo "===================="
        echo "ARTIFACT_ID=${{ inputs.ARTIFACT_ID }}"
        echo "======================"
      shell: bash

    - name: Rewrite version
      id: version
      run: |
        DATE_TIME=$(date '+%Y.%m.%d.%H.%M')
        SHA8=$(git rev-parse --short HEAD)
        VERSION="${DATE_TIME}-${SHA8}"
        find ${{ inputs.MODULE_PATH }} -name 'build.gradle.kts' -exec sed -i "s/APPOINTMENT-BOOKING-UNSET-VERSION/${VERSION}/g" {} +
        echo "VERSION=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "VERSION=${VERSION}"
      shell: bash
      env:
        TZ: Africa/Johannesburg


    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.1.0'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-kotlin-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-kotlin-

    - name: Create Gradle directories
      run: |
        mkdir -p ~/.gradle/caches
        mkdir -p ~/.gradle/wrapper
      shell: bash

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    # Download SPI modules built by separate build-spi-modules job with JDK 21
    - name: Download validate-credential-module JAR
      uses: actions/download-artifact@v4
      with:
        pattern: 'validate-credential-module-*'
        path: validate-credential-module/build/libs
        merge-multiple: true

    - name: Download generate-username-module JAR
      uses: actions/download-artifact@v4
      with:
        pattern: 'generate-username-module-*'
        path: generate-username-ui-register-module/build/libs
        merge-multiple: true

    - name: Verify SPI JARs
      run: |
        set +o pipefail  # Don't fail on broken pipe from head command
        echo "SPI JARs downloaded:"
        echo "=== validate-credential-module ==="
        ls -la validate-credential-module/build/libs/ || echo "validate-credential-module JARs not found"
        echo "=== generate-username-ui-register-module ==="
        ls -la generate-username-ui-register-module/build/libs/ || echo "generate-username-ui-register-module JARs not found"
        
        echo ""
        echo "=== Verifying JAR integrity ==="
        for jar in validate-credential-module/build/libs/*.jar generate-username-ui-register-module/build/libs/*.jar; do
          if [ -f "$jar" ]; then
            echo "Checking: $jar"
            # Verify JAR is valid zip
            if unzip -t "$jar" > /dev/null 2>&1; then
              echo "  ✓ JAR is valid"
              # List contents to verify structure
              echo "  Contents:"
              unzip -l "$jar" 2>/dev/null | grep -E "(META-INF/services|\.class)" | head -10 || true
            else
              echo "  ✗ JAR is CORRUPTED!"
              exit 1
            fi
          fi
        done
        echo "=== All JARs verified ==="
      shell: bash

    - name: Test with Gradle
      id: test
      run: ./gradlew  test   --no-daemon --max-workers=1
      shell: bash

    - name: Build with Gradle
      id: build
      run: |
        ./gradlew clean build  -x test --console=plain --no-daemon  -DexcludedTags=kafka
        ARTIFACT_PATH=$(pwd)/build/libs/${ARTIFACT_ID}-${VERSION}.jar
        echo "ARTIFACT_PATH=${ARTIFACT_PATH}" >> "$GITHUB_OUTPUT"
        echo "ARTIFACT_PATH=${ARTIFACT_PATH}"
      shell: bash
      env:
        VERSION: ${{ steps.version.outputs.VERSION }}
        ARTIFACT_ID: ${{ inputs.ARTIFACT_ID }}

    - name: Print Outputs
      run: |
        echo "=============="
        echo "VERSION: ${{ steps.version.outputs.VERSION }}" 
        echo "ARTIFACT_PATH: ${{ steps.build.outputs.ARTIFACT_PATH }}" 
        echo "==============="
      shell: bash

    - name: Create Text Summary of Failures
      if: failure()
      run: |
        # Find all XML result files and extract the failure messages into a txt file
        grep -hR "failure message" build/test-results/test/*.xml > test-failures.txt || echo "No failures found" > test-failures.txt
      shell: bash

    - name: Upload Text Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-failures-text
        path: test-failures.txt
    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.ARTIFACT_ID }}-${{ steps.version.outputs.VERSION }}
        path: ${{ steps.build.outputs.ARTIFACT_PATH }}
        retention-days: 1