name: "Update Keycloak SPI ConfigMap"
description: "Patches Keycloak SPI ConfigMap with latest JAR (base64 encoded)"

inputs:
  ORGANIZATION:
    description: "GitHub organization"
    required: true
  REPOSITORY:
    description: "Repository name"
    required: true
  MODULE_NAME:
    description: "Module name (generate-username or validate-credential)"
    required: true
  JAR_ARTIFACT_NAME:
    description: "Name of the uploaded JAR artifact"
    required: true
  VERSION:
    description: "Version of the JAR"
    required: true
  GIT_REPO_ACCESS_TOKEN:
    description: "GitHub token for pushing changes"
    required: true
  APP_GITHUB_EMAIL:
    description: "Git commit email"
    required: true
  APP_GITHUB_USERNAME:
    description: "Git commit username"
    required: true

outputs:
  CONFIGMAP_FILE:
    description: "Path to updated ConfigMap file"
    value: ${{ steps.config.outputs.CONFIGMAP_FILE }}

runs:
  using: "composite"
  steps:
    - name: Print Inputs
      run: |
        echo "======================"
        echo "MODULE_NAME=${{ inputs.MODULE_NAME }}"
        echo "JAR_ARTIFACT_NAME=${{ inputs.JAR_ARTIFACT_NAME }}"
        echo "VERSION=${{ inputs.VERSION }}"
        echo "======================"
      shell: bash

    - name: Clone repository
      run: |
        git clone https://${{ inputs.GIT_REPO_ACCESS_TOKEN }}@github.com/${{ inputs.ORGANIZATION }}/${{ inputs.REPOSITORY }}.git
      shell: bash

    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.JAR_ARTIFACT_NAME }}
        path: ./jar-artifact

    - name: Setup yq
      uses: chrisdickinson/setup-yq@latest
      with:
        yq-version: v4.29.2

    - name: Determine ConfigMap file
      id: config
      run: |
        if [ "${{ inputs.MODULE_NAME }}" == "generate-username" ]; then
          echo "CONFIGMAP_FILE=deploy-operation/helm/generate-username-spi-configmaps.yaml" >> $GITHUB_OUTPUT
          echo "JAR_KEY=generate-username-module-APPOINTMENT-BOOKING-UNSET-VERSION.jar" >> $GITHUB_OUTPUT
        elif [ "${{ inputs.MODULE_NAME }}" == "validate-credential" ]; then
          echo "CONFIGMAP_FILE=deploy-operation/helm/validate-credentials-spi-configmaps.yaml" >> $GITHUB_OUTPUT
          echo "JAR_KEY=validate-credential-module-APPOINTMENT-BOOKING-UNSET-VERSION.jar" >> $GITHUB_OUTPUT
        else
          echo "Error: Unknown module ${{ inputs.MODULE_NAME }}"
          exit 1
        fi
      shell: bash

    - name: Patch ConfigMap with JAR base64
      run: |
        cd ${{ inputs.REPOSITORY }}
        
        CONFIGMAP_FILE="${{ steps.config.outputs.CONFIGMAP_FILE }}"
        JAR_KEY="${{ steps.config.outputs.JAR_KEY }}"
        JAR_FILE=$(ls ../jar-artifact/*.jar | head -1)
        
        echo "JAR file: $(basename $JAR_FILE)"
        echo "ConfigMap: ${CONFIGMAP_FILE}"
        echo "JAR key: ${JAR_KEY}"
        
        # Base64 encode and patch binaryData in one step
        JAR_BASE64=$(base64 -w 0 "$JAR_FILE")
        
        # Patch the binaryData field with new JAR content
        yq -i ".binaryData.\"${JAR_KEY}\" = \"${JAR_BASE64}\"" "${CONFIGMAP_FILE}"
        
        # Update version in data section
        yq -i ".data.version = \"${{ inputs.VERSION }}\"" "${CONFIGMAP_FILE}"
        
        echo "ConfigMap patched successfully"
      shell: bash

    - name: Commit and Push
      run: |
        cd ${{ inputs.REPOSITORY }}
        if [[ `git status --porcelain --untracked-files=no` ]]; then
          git config user.email "${{ inputs.APP_GITHUB_EMAIL }}"
          git config user.name "${{ inputs.APP_GITHUB_USERNAME }}"
          git add .
          git commit -m "Update ${{ inputs.MODULE_NAME }} SPI to ${{ inputs.VERSION }}"
          git push
          echo "Pushed SPI update"
        else
          echo "No changes detected"
        fi
      shell: bash
