name: Deploy Docker Image to Docker Hub

description: |
  Retags an existing Docker Hub image with a new tag.
  Only needed when promoting images (e.g., adding 'prod' tag).
  Note: docker-build already pushes the image with version and latest tags.

inputs:
  DOCKERHUB_USERNAME:
    description: "Docker Hub username"
    required: true
  DOCKERHUB_PASSWORD:
    description: "Docker Hub password or access token"
    required: true
  IMAGE_NAME:
    description: "Full source image name with tag (e.g., username/repo:version) - from build-docker output"
    required: true
  TARGET_TAG:
    description: "Target tag for the image (e.g., 'prod', 'staging')"
    required: true

outputs:
  DOCKERHUB_IMAGE:
    description: "Full Docker Hub image name with new tag"
    value: ${{ steps.push.outputs.DOCKERHUB_IMAGE }}

runs:
  using: "composite"
  steps:
    - name: Print Inputs
      run: |
        echo "======================"
        echo "IMAGE_NAME=${{ inputs.IMAGE_NAME }}"
        echo "TARGET_TAG=${{ inputs.TARGET_TAG }}"
        echo "======================"
      shell: bash

    - name: Login to Docker Hub
      run: |
        echo "${{ inputs.DOCKERHUB_PASSWORD }}" | docker login -u "${{ inputs.DOCKERHUB_USERNAME }}" --password-stdin
      shell: bash

    - name: Pull, Retag and Push
      id: push
      run: |
        SOURCE_IMAGE="${{ inputs.IMAGE_NAME }}"
        REPO="${SOURCE_IMAGE%:*}"
        DOCKERHUB_IMAGE="${REPO}:${{ inputs.TARGET_TAG }}"
        
        echo "Pulling: ${SOURCE_IMAGE}"
        docker pull "${SOURCE_IMAGE}"
        
        echo "Retagging as: ${DOCKERHUB_IMAGE}"
        docker tag "${SOURCE_IMAGE}" "${DOCKERHUB_IMAGE}"
        
        echo "Pushing: ${DOCKERHUB_IMAGE}"
        docker push "${DOCKERHUB_IMAGE}"
        
        echo "DOCKERHUB_IMAGE=${DOCKERHUB_IMAGE}" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Logout
      if: always()
      run: docker logout || true
      shell: bash
