name: Build Keycloak SPI Module
description: 'Builds a Keycloak SPI module with JDK 21 and uploads as artifact'

inputs:
  MODULE_PATH:
    description: 'Path to the module directory (e.g., generate-username-ui-register-module)'
    required: true
  MODULE_NAME:
    description: 'Name for the artifact (e.g., generate-username-module)'
    required: true
  JAVA_VERSION:
    description: 'Java version to use for building'
    required: false
    default: '21'
  RETENTION_DAYS:
    description: 'Number of days to retain the artifact'
    required: false
    default: '15'

outputs:
  VERSION:
    description: 'The version of the built module'
    value: ${{ steps.version.outputs.VERSION }}
  JAR_PATH:
    description: 'Path to the built JAR file'
    value: ${{ steps.build.outputs.JAR_PATH }}
  ARTIFACT_NAME:
    description: 'Name of the uploaded artifact'
    value: ${{ steps.artifact.outputs.ARTIFACT_NAME }}

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.JAVA_VERSION }}
        distribution: 'temurin'

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-spi-${{ inputs.MODULE_NAME }}-${{ hashFiles(format('{0}/**/*.gradle*', inputs.MODULE_PATH), format('{0}/**/gradle-wrapper.properties', inputs.MODULE_PATH)) }}
        restore-keys: |
          ${{ runner.os }}-gradle-spi-${{ inputs.MODULE_NAME }}-
          ${{ runner.os }}-gradle-spi-

    - name: Cache SPI module build
      uses: actions/cache@v4
      id: spi-build-cache
      with:
        path: ${{ inputs.MODULE_PATH }}/build/libs/*.jar
        key: spi-${{ inputs.MODULE_NAME }}-${{ runner.os }}-${{ hashFiles(format('{0}/src/**', inputs.MODULE_PATH), format('{0}/build.gradle.kts', inputs.MODULE_PATH)) }}

    - name: Build module with Gradle
      id: build
      if: steps.spi-build-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.MODULE_PATH }}
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew clean build -x test --no-daemon
        echo "Built JAR files:"
        ls -la build/libs/
        JAR_FILE=$(ls build/libs/*.jar | head -1)
        echo "JAR_PATH=${JAR_FILE}" >> $GITHUB_OUTPUT

    - name: Get version
      id: version
      working-directory: ${{ inputs.MODULE_PATH }}
      shell: bash
      run: |
        chmod +x ./gradlew
        VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
        if [ -z "$VERSION" ] || [ "$VERSION" == "unspecified" ]; then
          VERSION="1.0.0-$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Module version: ${VERSION}"

    - name: Set artifact name
      id: artifact
      shell: bash
      run: |
        ARTIFACT_NAME="${{ inputs.MODULE_NAME }}-${{ steps.version.outputs.VERSION }}"
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
        echo "JAR_DIR=${{ inputs.MODULE_PATH }}/build/libs" >> $GITHUB_OUTPUT

    - name: Prepare artifact directory structure
      shell: bash
      run: |
        # Ensure the directory structure exists
        mkdir -p ${{ inputs.MODULE_PATH }}/build/libs
        echo "JAR files in build/libs:"
        ls -la ${{ inputs.MODULE_PATH }}/build/libs/ || echo "No JAR files found"

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.ARTIFACT_NAME }}
        path: ${{ inputs.MODULE_PATH }}/build/libs/
        retention-days: ${{ inputs.RETENTION_DAYS }}
        if-no-files-found: error

